In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import pickle

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error
from sklearn.model_selection import train_test_split, cross_val_score, cross_validate
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [88]:
df = pd.read_csv('data/28.6 vehicles_dataset.csv')
df.head()

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,type,paint_color,image_url,description,county,state,lat,long,posting_date,price_category
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020.0,ram,2500 crew cab big horn,good,NaN,...,pickup,silver,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,NaN,tn,35.060000,-85.250000,2021-04-17T12:30:50-0400,high
1,7316380095,https://newjersey.craigslist.org/ctd/d/carlsta...,north jersey,https://newjersey.craigslist.org,16942,2016.0,ford,explorer 4wd 4dr xlt,NaN,6 cylinders,...,SUV,black,https://images.craigslist.org/00x0x_26jl9F0cnL...,***Call Us for more information at: 201-635-14...,NaN,nj,40.821805,-74.061962,2021-05-03T15:40:21-0400,medium
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017.0,volkswagen,golf r hatchback,good,NaN,...,sedan,NaN,https://images.craigslist.org/00y0y_eeZjWeiSfb...,Carvana is the safer way to buy a car During t...,NaN,ca,33.779214,-84.411811,2021-04-28T03:52:20-0700,high
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013.0,toyota,rav4,NaN,NaN,...,wagon,white,https://images.craigslist.org/00606_iGe5iXidib...,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,NaN,nc,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium
4,7316474668,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800,2021.0,nissan,altima,new,4 cylinders,...,NaN,NaN,https://images.craigslist.org/00V0V_3pSOiPZ3Sd...,2021 Nissan Altima Sv with Only 8 K Miles Titl...,NaN,ny,40.654800,-73.609700,2021-05-03T18:32:06-0400,medium

# Data Preparation

In [3]:
df.shape

(10050, 27)

In [4]:
df.columns

Index(['id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer',
       'model', 'condition', 'cylinders', 'fuel', 'odometer', 'title_status',
       'transmission', 'VIN', 'drive', 'size', 'type', 'paint_color',
       'image_url', 'description', 'county', 'state', 'lat', 'long',
       'posting_date', 'price_category'],
      dtype='object')

In [89]:
df.describe(include='all')

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,type,paint_color,image_url,description,county,state,lat,long,posting_date,price_category
count,1.005000e+04,10050,10050,10050,1.005000e+04,10014.000000,9665,9921,6268,5953,...,7845,7087,10048,10048,0.0,10050,9951.000000,9951.000000,10048,10050
unique,NaN,10000,393,405,NaN,NaN,39,3466,6,8,...,13,12,9081,9845,NaN,51,NaN,NaN,9957,3
top,NaN,https://roswell.craigslist.org/cto/d/artesia-1...,"kansas city, MO",https://kansascity.craigslist.org,NaN,NaN,ford,f-150,good,6 cylinders,...,sedan,white,https://images.craigslist.org/00N0N_1xMPvfxRAI...,PLEASE VIEW THE FREE CARFAX HISTORY REPORT AT ...,NaN,ca,NaN,NaN,2021-04-13T09:11:02-0500,high
freq,NaN,2,86,86,NaN,NaN,1647,151,3134,2288,...,1981,1916,191,7,NaN,1113,NaN,NaN,3,3514
mean,7.311544e+09,NaN,NaN,NaN,2.068429e+04,2010.917815,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,38.590164,-94.161564,NaN,NaN
std,4.475414e+06,NaN,NaN,NaN,1.243216e+05,9.697849,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.844756,18.123096,NaN,NaN
min,7.208550e+09,NaN,NaN,NaN,5.000000e+02,1915.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-67.144243,-158.069300,NaN,NaN
25%,7.308193e+09,NaN,NaN,NaN,7.900000e+03,2008.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,34.830000,-110.447150,NaN,NaN
50%,7.312756e+09,NaN,NaN,NaN,1.574950e+04,2013.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,39.285100,-87.999100,NaN,NaN
75%,7.315275e+09,NaN,NaN,NaN,2.799000e+04,2017.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,42.427590,-80.830000,NaN,NaN
max,7.317090e+09,NaN,NaN,NaN,1.234568e+07,2022.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,64.947500,173.885502,NaN,NaN

### Data Cleaning

In [90]:
#Выведем наименование каждого столюца и количество незаполненных значений
df.isna().sum().sort_values()

id                    0
state                 0
price                 0
price_category        0
region                0
url                   0
region_url            0
description           2
image_url             2
posting_date          2
year                 36
odometer             43
transmission         45
fuel                 63
lat                  99
long                 99
model               129
title_status        166
manufacturer        385
type               2205
paint_color        2963
drive              3024
condition          3782
VIN                3964
cylinders          4097
size               7225
county            10050
dtype: int64

In [91]:
missing_values = ((df.isna().sum() / len(df)) * 100).sort_values(ascending=False)
print('Процент пропущенных значений:')
print(missing_values.round(2))

Процент пропущенных значений:
county            100.00
size               71.89
cylinders          40.77
VIN                39.44
condition          37.63
drive              30.09
paint_color        29.48
type               21.94
manufacturer        3.83
title_status        1.65
model               1.28
long                0.99
lat                 0.99
fuel                0.63
transmission        0.45
odometer            0.43
year                0.36
posting_date        0.02
image_url           0.02
description         0.02
state               0.00
id                  0.00
url                 0.00
price               0.00
region_url          0.00
region              0.00
price_category      0.00
dtype: float64

#### Обработка пропусков в колонке county

In [92]:
#Столбец County должен содержать данные о стране, но так как наш датасет содержит информацию об автомобилях в США, 
# то, очевидно, что все значения должны быть одинаковые и никак не влиять на модель. Этот столбец можно удалить.
df.drop(columns=['county'], axis=1, inplace=True)

#### Обработка пропусков в колонке size

In [93]:
#получим описание колонки size
df['size'].describe()

count          2825
unique            4
top       full-size
freq           1476
Name: size, dtype: object

In [94]:
#списко уникальных значений колонки size
df['size'].unique()

array([nan, 'full-size', 'mid-size', 'sub-compact', 'compact'],
      dtype=object)

In [95]:
#Колонка может принимаеть только четыре значения

In [96]:
#посмотрим на распределение значений
df['size'].value_counts(normalize=True)

full-size      0.522478
mid-size       0.291681
compact        0.162124
sub-compact    0.023717
Name: size, dtype: float64

In [97]:
#заполним пропуски значением other
df['size'] = df['size'].fillna('other')

#### Обработка пропусков в колонке cylinders

In [98]:
#получим описание колонки cylinders
df['cylinders'].describe()

count            5953
unique              8
top       6 cylinders
freq             2288
Name: cylinders, dtype: object

In [99]:
#списко уникальных значений колонки size
df['cylinders'].unique()

array([nan, '6 cylinders', '4 cylinders', '8 cylinders', '3 cylinders',
       '5 cylinders', 'other', '10 cylinders', '12 cylinders'],
      dtype=object)

In [100]:
#посмотрим на распределение значений
df['cylinders'].value_counts(normalize=True)

6 cylinders     0.384344
4 cylinders     0.306568
8 cylinders     0.289938
5 cylinders     0.007727
10 cylinders    0.004871
other           0.004200
3 cylinders     0.002184
12 cylinders    0.000168
Name: cylinders, dtype: float64

In [101]:
#заполним пропуски значением other
df['cylinders'] = df['cylinders'].fillna('other')

#### Обработка пропусков в колонке VIN

In [102]:
#заполним пропуски значением other
#все значения VIN должны быть уникальными, а пропусков много, поэтому заполним пропуски значением other
df['VIN'] = df['VIN'].fillna('other')

#### Обработка пропусков в колонке condition

In [103]:
df['condition'].unique()

array(['good', nan, 'new', 'excellent', 'like new', 'fair', 'salvage'],
      dtype=object)

In [104]:
# Посмотрим на распределение значений в колонке
df['condition'].value_counts(normalize=True)

good         0.500000
excellent    0.387524
like new     0.076899
fair         0.028558
new          0.004946
salvage      0.002074
Name: condition, dtype: float64

In [105]:
# Заполним пропуски самым популярным занчением
popular_condition = df['condition'].value_counts().idxmax()
df.condition = df.condition.fillna(popular_condition)

#### Обработка пропусков в колонке drive

In [106]:
df['drive'].unique()

array(['4wd', nan, 'fwd', 'rwd'], dtype=object)

In [107]:
# Посмотрим на распределение значений в колонке
df['drive'].value_counts(normalize=True)

4wd    0.434671
fwd    0.364788
rwd    0.200541
Name: drive, dtype: float64

In [108]:
#заполним пропуски значением other
df['drive'] = df['drive'].fillna('other')

#### Обработка пропусков в колонке paint_color

In [109]:
df['paint_color'].unique()

array(['silver', 'black', nan, 'white', 'blue', 'red', 'green', 'grey',
       'custom', 'orange', 'yellow', 'brown', 'purple'], dtype=object)

In [110]:
# Посмотрим на распределение значений в колонке
df['paint_color'].value_counts(normalize=True)

white     0.270354
black     0.207845
silver    0.146889
red       0.104558
blue      0.103006
grey      0.084803
green     0.024411
custom    0.021730
brown     0.020319
yellow    0.007478
orange    0.007196
purple    0.001411
Name: paint_color, dtype: float64

In [111]:
#заполним пропуски значением other
df['paint_color'] = df['paint_color'].fillna('other')

#### Обработка пропусков в колонке type

In [112]:
df['type'].unique()

array(['pickup', 'SUV', 'sedan', 'wagon', nan, 'coupe', 'hatchback',
       'van', 'mini-van', 'other', 'convertible', 'truck', 'bus',
       'offroad'], dtype=object)

In [113]:
# Посмотрим на распределение значений в колонке
df['type'].value_counts(normalize=True)

sedan          0.252518
SUV            0.230083
pickup         0.136520
truck          0.098152
other          0.066157
coupe          0.056469
hatchback      0.052772
wagon          0.032505
van            0.028936
convertible    0.026004
mini-van       0.014404
bus            0.002804
offroad        0.002677
Name: type, dtype: float64

In [114]:
#заполним пропуски значением other
df['type'] = df['type'].fillna('other')

#### Обработка пропусков в колонке manufacturer

In [115]:
df = df[df.manufacturer.notna()]

#### Обработка пропусков в колонке title_status

In [116]:
# Посмотрим на распределение значений в колонке
df['title_status'].value_counts(normalize=True)

clean         0.968247
rebuilt       0.017453
salvage       0.009252
lien          0.003575
missing       0.001262
parts only    0.000210
Name: title_status, dtype: float64

In [117]:
# Заполним пропуски самым популярным занчением
popular_status = df['title_status'].value_counts().idxmax()
df.title_status = df.title_status.fillna(popular_status)

#### Обработка пропусков в колонке model

In [118]:
# Посмотрим на распределение значений в колонке
df['model'].value_counts(normalize=True)

f-150                        0.015831
silverado 1500               0.011533
1500                         0.010589
camry                        0.008073
wrangler                     0.007758
                               ...
forester xt                  0.000105
q50 2.0t luxe sedan 4d       0.000105
silverado diesel 3500        0.000105
silverado 1500 ls            0.000105
a3 2.0t premium plus pzev    0.000105
Name: model, Length: 3186, dtype: float64

In [119]:
#заполним пропуски значением other
df.model = df['model'].fillna('other')

#### Обработка пропусков в колонке long, lat, odometer, transmission, fuel

In [120]:
#В этих колонках мало пропусков, поэтому просто удалим строки с пустыми значениями
df = df[df.long.notna()]
df = df[df.lat.notna()]

In [121]:
df = df[df.odometer.notna()]
df = df[df.transmission.notna()]
df = df[df.fuel.notna()]

In [122]:
df.isna().sum().sort_values()

id                0
long              0
lat               0
state             0
description       0
image_url         0
paint_color       0
type              0
size              0
drive             0
VIN               0
transmission      0
title_status      0
odometer          0
fuel              0
cylinders         0
condition         0
model             0
manufacturer      0
year              0
price             0
region_url        0
region            0
url               0
posting_date      0
price_category    0
dtype: int64

In [123]:
# Все пропуски обработаны

#### Обработка выбросов в колонке year

In [124]:
df.year.describe()

count    9448.000000
mean     2011.143628
std         9.233318
min      1915.000000
25%      2008.000000
50%      2013.000000
75%      2017.000000
max      2022.000000
Name: year, dtype: float64

In [125]:
#Получим границы нормальных значений, использую интерквартильный размах
def colculate_outliners(data):
    q25 = data.quantile(0.25)
    q75 = data.quantile(0.75)
    iqr = q75 - q25
    boundaries = (q25 - 1.5 * iqr, q75 + 1.5 * iqr)
    return boundaries
boundaries = colculate_outliners(df.year)
boundaries

(1994.5, 2030.5)

In [126]:
#Количество выбросов
is_outliner = (df.year < boundaries[0]) | (df.year > boundaries[1])
is_outliner.sum()

335

In [127]:
#доля выбросов
is_outliner.sum() / len(df)

0.03545723962743438

In [128]:
#Так как выбросы в годе выпуска находятся среди минимальных значений, 
#заполним те значения, которые являются выбросами, значением нижней границы.
df.loc[is_outliner, 'year'] = int(boundaries[0]+0.5)

In [129]:
df.year.describe()

count    9448.000000
mean     2011.813717
std         6.330395
min      1995.000000
25%      2008.000000
50%      2013.000000
75%      2017.000000
max      2022.000000
Name: year, dtype: float64

#### Обработка выбросов в колонке odometer

In [130]:
df.odometer.describe()

count    9.448000e+03
mean     9.508974e+04
std      7.773426e+04
min      0.000000e+00
25%      3.919675e+04
50%      8.900000e+04
75%      1.373275e+05
max      2.070000e+06
Name: odometer, dtype: float64

In [131]:
#Получим границы нормальных значений, использую интерквартильный размах
def colculate_outliners(data):
    q25 = data.quantile(0.25)
    q75 = data.quantile(0.75)
    iqr = q75 - q25
    boundaries = (q25 - 1.5 * iqr, q75 + 1.5 * iqr)
    return boundaries
boundaries_od = colculate_outliners(df.odometer)
boundaries_od

(-107999.375, 284523.625)

In [132]:
#Количество выбросов
is_outliner_od = (df.odometer < boundaries_od[0]) | (df.odometer > boundaries_od[1])
is_outliner_od.sum()

72

In [133]:
#доля выбросов
is_outliner_od.sum() / len(df)

0.007620660457239628

In [134]:
#Так как выбросы в колонке odometer находятся среди максимальных значений, 
#заполним те значения, которые являются выбросами, значением верхней границы.
df.loc[is_outliner_od, 'odometer'] = boundaries_od[1]

In [135]:
df.odometer.describe()

count      9448.000000
mean      93508.198984
std       62923.297969
min           0.000000
25%       39196.750000
50%       89000.000000
75%      137327.500000
max      284523.625000
Name: odometer, dtype: float64

# Data engineering

In [136]:
#В датасете есть следующие котегориальные переменные:
#state
#paint_color
#type
#size
#drive
#transmission
#title_status
#fuel
#cylinders
#condition
#model
#manufacturer
#region

#### Работа над колонкой model

In [137]:
df.model.value_counts()

f-150                        144
other                        127
silverado 1500               104
1500                          99
camry                         75
                            ...
forte s sedan 4d               1
altima 2.5s                    1
cx-5 grand touring             1
ls 460 lwb                     1
a3 2.0t premium plus pzev      1
Name: model, Length: 3136, dtype: int64

In [138]:
#Сократим количество уникальных значений
df['short_model'] = df.apply(lambda x: x.model.split()[0], axis=1)
df.short_model.value_counts()

silverado    408
1500         206
wrangler     204
grand        199
f-150        197
            ...
530            1
phaeton        1
astro          1
5500hd         1
gs350          1
Name: short_model, Length: 799, dtype: int64

## Стандартизиреум котегориальные переменные

In [55]:
# создадим отдельный датафрейм для котегориальных переменных
# 
data = df[['short_model', 'paint_color', 'type', 'size', 'drive', 'fuel', 'cylinders', 'region', 'condition',  'transmission', 'state', 'manufacturer', 'region', 'title_status']]
data.head()

,short_model,paint_color,type,size,drive,fuel,cylinders,region,condition,transmission,state,manufacturer,region,title_status
0,2500,silver,pickup,other,4wd,diesel,other,chattanooga,good,other,tn,ram,chattanooga,clean
2,golf,other,sedan,other,other,gas,other,reno / tahoe,good,other,ca,volkswagen,reno / tahoe,clean
3,rav4,white,wagon,other,fwd,gas,other,fayetteville,good,automatic,nc,toyota,fayetteville,clean
4,altima,other,other,other,other,gas,4 cylinders,new york city,new,automatic,ny,nissan,new york city,clean
5,1,black,coupe,other,other,other,other,knoxville,good,other,tn,bmw,knoxville,clean

In [139]:
ohe = OneHotEncoder(sparse=False)

In [140]:
ohe.fit(df[['short_model', 'paint_color', 'type', 'size', 'drive', 'fuel', 'cylinders', 'region', 'condition',  'transmission', 'state', 'manufacturer', 'region', 'title_status']])

OneHotEncoder(sparse=False)

In [141]:
ohe_category_var = ohe.transform(df[['short_model', 'paint_color', 'type', 'size', 'drive', 'fuel', 'cylinders', 'region', 'condition',  'transmission', 'state', 'manufacturer', 'region', 'title_status']])

In [142]:
# Ваш код здесь
df[ohe.get_feature_names()] = ohe_category_var
df.head()

J:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3678: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  self[col] = igetitem(value, i)

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,x12_youngstown,x12_yuba-sutter,x12_yuma,x12_zanesville / cambridge,x13_clean,x13_lien,x13_missing,x13_parts only,x13_rebuilt,x13_salvage
0,7308295377,https://chattanooga.craigslist.org/ctd/d/chatt...,chattanooga,https://chattanooga.craigslist.org,54990,2020.0,ram,2500 crew cab big horn,good,other,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,7313733749,https://reno.craigslist.org/ctd/d/atlanta-2017...,reno / tahoe,https://reno.craigslist.org,35590,2017.0,volkswagen,golf r hatchback,good,other,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,7308210929,https://fayetteville.craigslist.org/ctd/d/rale...,fayetteville,https://fayetteville.craigslist.org,14500,2013.0,toyota,rav4,good,other,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,7316474668,https://newyork.craigslist.org/lgi/cto/d/baldw...,new york city,https://newyork.craigslist.org,21800,2021.0,nissan,altima,new,4 cylinders,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5,7303797340,https://knoxville.craigslist.org/ctd/d/knoxvil...,knoxville,https://knoxville.craigslist.org,14590,2012.0,bmw,1 series 128i coupe 2d,good,other,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [143]:
#надо будет удалить старые колонки
df.columns

Index(['id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer',
       'model', 'condition', 'cylinders',
       ...
       'x12_youngstown', 'x12_yuba-sutter', 'x12_yuma',
       'x12_zanesville / cambridge', 'x13_clean', 'x13_lien', 'x13_missing',
       'x13_parts only', 'x13_rebuilt', 'x13_salvage'],
      dtype='object', length=1762)

In [144]:
#создадим отдельный датафрейм, в котором уберем все старые категориальные колонки, но оставим данные преобразованные с помощью OneHotEncoder
df_ohe = df.drop(columns = ['model', 'short_model', 'paint_color', 'type', 'size', 'drive', 'fuel', 'cylinders', 'region', 'condition',  'transmission', 'state', 'manufacturer', 'region', 'title_status'],axis = 1)
#дополнительно удалим колонки, которые не несут в себе существенной информации об автомобиле:
# 'id' - идентификатор записи
# 'url' - URL записи о продаже
# 'region_url' - URL региона
# 'image_url' - URL изображения

# 'VIN' я понимаю, что этот столбец спорный. Да в VIN закодирована информация об автомобиле. 
# Но я уверен, что если модель и сможет найти какие-то зависимости, то они не будут иметь ничего общего с объективной действительностью.
# Каждй производитель по своему кодирует VIN. Каждый номер уникальный. Поэтому, я думаю, что пользы от него столько же сколько и от колонки id
df_ohe_1 = df_ohe.drop(columns = ['id', 'url', 'region_url', 'VIN', 'image_url'], axis = 1)

In [62]:
col = df_ohe_1.columns
for i in col:
    print(i)

price
year
odometer
description
lat
long
posting_date
price_category
x0_-benz
x0_1
x0_124
x0_128i
x0_135i
x0_1500
x0_2
x0_200
x0_2018
x0_210
x0_240
x0_2500
x0_2500hd
x0_280zx
x0_3
x0_3-series
x0_3-window
x0_3.2
x0_300
x0_300-series
x0_300c
x0_300s
x0_300zx
x0_3100
x0_318i
x0_320i
x0_323i
x0_325ci
x0_325i
x0_325is
x0_325xi
x0_328
x0_328ci
x0_328d
x0_328i
x0_328xi
x0_330i
x0_330xi
x0_335i
x0_335xi
x0_350
x0_3500
x0_3500hd
x0_350z
x0_370z
x0_380sl
x0_3i
x0_4
x0_4-runner
x0_428
x0_430i
x0_435i
x0_440xi
x0_4500
x0_488
x0_4runner
x0_4x4
x0_5
x0_5-series
x0_50
x0_500
x0_500c
x0_500l
x0_500x
x0_525i
x0_528i
x0_528xi
x0_530
x0_530i
x0_535i
x0_535xi
x0_540i
x0_545i
x0_5500
x0_5500hd
x0_550i
x0_5th
x0_6
x0_640
x0_645ci
x0_650i
x0_650xi
x0_7
x0_750
x0_750i
x0_750xi
x0_86
x0_911
x0_914
x0_928
x0_944
x0_a-class
x0_a3
x0_a3,
x0_a4
x0_a5
x0_a6
x0_a7
x0_a8
x0_acadia
x0_accent
x0_accord
x0_allante
x0_allroad
x0_altima
x0_arcadia
x0_armada
x0_arteon
x0_ascent
x0_aspen
x0_astra
x0_astro
x0_atlas
x0_ats
x0_aura
x0_autobiography
x0_avalanche
x0_avalon
x0_avanger
x0_avenger
x0_aveo
x0_aviator
x0_azera
x0_aztek
x0_b-class
x0_b-series
x0_b2200
x0_b2300
x0_b2600i
x0_baja
x0_beetle
x0_bel
x0_belair
x0_benz
x0_blackwood
x0_blazer
x0_bolt
x0_bonanza
x0_bonneville
x0_boxster
x0_bronco
x0_brz
x0_bug
x0_bus
x0_c
x0_c-10
x0_c-class
x0_c-hr
x0_c-max
x0_c/k
x0_c10
x0_c250
x0_c280
x0_c300
x0_c4500
x0_c5500
x0_c60
x0_c6500
x0_c70
x0_c8500
x0_cabellero
x0_cabrio
x0_cadenza
x0_caliber
x0_camaro
x0_camary
x0_camero
x0_camry
x0_canyon
x0_capri
x0_caprice
x0_captiva
x0_caravan
x0_caravan/grand
x0_cargo
x0_cascada
x0_cavalier
x0_cayenne
x0_cayman
x0_cc
x0_cc4500
x0_century
x0_certified
x0_challenger
x0_charger
x0_cherokee
x0_chevelle
x0_city
x0_civic
x0_cj-5
x0_cj2a
x0_cj5
x0_cj7
x0_cj8
x0_cl-class
x0_cla
x0_cla-class
x0_clarity
x0_classic
x0_classuc
x0_clk
x0_clk-class
x0_clk350
x0_cls-class
x0_cls550
x0_clubman
x0_cmax
x0_cobalt
x0_coe
x0_colbalt
x0_colorado
x0_comet
x0_commander
x0_compass
x0_concorde
x0_conquest
x0_continental
x0_convertible
x0_cooper
x0_corolla
x0_corsair
x0_corvette
x0_cougar
x0_country
x0_countryman
x0_coupe
x0_cr-v
x0_crew
x0_crossfire
x0_crosstour
x0_crosstrek
x0_crown
x0_cruze
x0_crv
x0_crz
x0_ct
x0_ct4
x0_ct5
x0_ct6
x0_cts
x0_cts4
x0_cube
x0_cummins
x0_cvr
x0_cx-3
x0_cx-5
x0_cx-7
x0_cx-9
x0_cx7
x0_cx9
x0_d50
x0_dakota
x0_dart
x0_davidson
x0_dealer*
x0_defender
x0_deisel
x0_deluxe
x0_denali
x0_deville
x0_diesel
x0_discovery
x0_dts
x0_dump
x0_duramax
x0_durango
x0_durangon
x0_e
x0_e-150
x0_e-250
x0_e-350
x0_e-450
x0_e-class
x0_e-golf
x0_e-pace
x0_e-series
x0_e150
x0_e250
x0_e320
x0_e350
x0_e450
x0_e46
x0_e500
x0_echo
x0_eclipse
x0_econoline
x0_ecosport
x0_edge
x0_el
x0_elantra
x0_elcamino
x0_eldorado
x0_element
x0_enclave
x0_encore
x0_endeavor
x0_envision
x0_envoy
x0_eos
x0_eqinox
x0_equinox
x0_es
x0_es300
x0_es330
x0_es350
x0_escalade
x0_escape
x0_escape-se,
x0_escort
x0_eurovan
x0_evoque
x0_excursion
x0_expedition
x0_explorer
x0_express
x0_f
x0_f-100
x0_f-150
x0_f-250
x0_f-250sd
x0_f-350
x0_f-350sd
x0_f-450
x0_f-450sd
x0_f-550
x0_f-550sd
x0_f-650
x0_f-750
x0_f-pace
x0_f-type
x0_f1
x0_f100
x0_f150
x0_f250
x0_f350
x0_f430
x0_f450
x0_f450sd
x0_f50
x0_f550
x0_f600
x0_f650
x0_f700
x0_f750
x0_falcon
x0_fe
x0_fiero
x0_fiesta
x0_firebird
x0_fit
x0_five
x0_fj
x0_fj40
x0_fleetmaster
x0_fleetwood
x0_flex
x0_focus
x0_forester
x0_forte
x0_forte5
x0_foxbody
x0_freestar
x0_freestyle
x0_frontier
x0_fusion
x0_fuso
x0_fx35
x0_fx45
x0_g
x0_g-class
x0_g.
x0_g20
x0_g30
x0_g35
x0_g35x
x0_g37
x0_g37s
x0_g37x
x0_g4500
x0_g5
x0_g6
x0_g8
x0_galant
x0_genesis
x0_ghia
x0_gl
x0_gl-class
x0_gl450
x0_gla
x0_gla-class
x0_gladiator
x0_glc
x0_glc-class
x0_gle
x0_gle-class
x0_glk
x0_glk-class
x0_glk350
x0_gls
x0_gmt-400
x0_golf
x0_gr
x0_grand
x0_grandville
x0_grumman
x0_gs
x0_gs350
x0_gs430
x0_gt
x0_gt-r
x0_gti
x0_gto
x0_gx
x0_gx460
x0_gx470
x0_hardbody
x0_hardtop
x0_hearse
x0_hhr
x0_hiace
x0_high
x0_highlander
x0_hr-v
x0_hse
x0_i-miev
x0_i3
x0_i30
x0_i35
x0_i8
x0_ilx
x0_impala
x0_impreza
x0_insight
x0_ion
x0_ioniq
x0_is
x0_is250
x0_is300
x0_isf
x0_jetta
x0_jimmy
x0_jouney
x0_journey
x0_juke
x0_jx35
x0_k10
x0_k20
x0_k30
x0_k5
x0_k900
x0_kicks
x0_kodiak
x0_l
x0_l300
x0_lacrosse
x0_lancer
x0_land
x0_landcruiser
x0_leaf
x0_legacy
x0_legend
x0_lemans
x0_lesabre
x0_liberty
x0_lifted
x0_lightning
x0_limousine
x0_long
x0_lr2
x0_lr3
x0_lr4
x0_ls
x0_ltd
x0_lucerne
x0_lx
x0_lx450
x0_m
x0_m-class
x0_m3
x0_m35
x0_m35s
x0_m4
x0_m5
x0_macan
x0_magnum
x0_malibu
x0_mallinia
x0_marineer,premier
x0_mariner
x0_mark
x0_matrix
x0_maxima
x0_maximum
x0_maybach
x0_mazda2
x0_mazda3
x0_mazda5
x0_mazda6
x0_mazda6i
x0_md-x
x0_mdx
x0_mercedes-amg
x0_metris
x0_miata
x0_mighty
x0_milan
x0_mirage
x0_mkc
x0_mks
x0_mkt
x0_mkx
x0_mkz
x0_ml
x0_ml350
x0_ml500
x0_model
x0_monte
x0_montero
x0_mountaineer
x0_mpv
x0_mr2
x0_murano
x0_mustang
x0_mx-5
x0_nautilus
x0_navigator
x0_neon
x0_new
x0_newport
x0_niro
x0_nitro
x0_nova
x0_nv
x0_nv1500
x0_nv200
x0_nv2500
x0_nv2500hd
x0_nx
x0_nx300
x0_oddyssey
x0_odyssey
x0_optima
x0_optimia
x0_other
x0_outback
x0_outlander
x0_outlook
x0_paceman
x0_pacifica
x0_panamera
x0_panel
x0_park
x0_passat
x0_passport
x0_pathfinder
x0_patriot
x0_phaeton
x0_pick
x0_pickup
x0_pilot
x0_prelude
x0_prius
x0_prizm
x0_promaster
x0_protege
x0_pt
x0_putback
x0_q3
x0_q5
x0_q50
x0_q60
x0_q7
x0_q70
x0_q8
x0_quattro
x0_quest
x0_qx50
x0_qx56
x0_qx60
x0_qx70
x0_qx80
x0_r-class
x0_r32
x0_rabbit
x0_rainier
x0_ram1500
x0_ramcharger
x0_range
x0_ranger
x0_rat
x0_rav
x0_rav4
x0_rc
x0_rdx
x0_reatta
x0_rebel
x0_regal
x0_rendezvous
x0_renegade
x0_replica
x0_ridgeline
x0_rio
x0_rivera
x0_riviera
x0_rl
x0_rlx
x0_roadmaster
x0_roadster
x0_rogue
x0_romeo
x0_rondo
x0_rouge
x0_routan
x0_rs
x0_rsx
x0_rx
x0_rx-8
x0_rx300
x0_rx330
x0_rx350
x0_rx400h
x0_rx7
x0_rx8
x0_s
x0_s-class
x0_s/w
x0_s10
x0_s2000
x0_s3
x0_s320
x0_s4
x0_s40
x0_s430
x0_s5
x0_s500
x0_s6
x0_s60
x0_s7
x0_s70
x0_s8
x0_s90
x0_sable
x0_santa
x0_sante
x0_savana
x0_sc
x0_sc2
x0_sc300
x0_school
x0_scion
x0_sebring
x0_sedan
x0_sedona
x0_seirra
x0_sentra
x0_sequioa
x0_sequoia
x0_seville
x0_sienna
x0_sierra
x0_sierra1500
x0_silverado
x0_sky
x0_skylark
x0_sl-class
x0_sl2
x0_sl500
x0_sl55
x0_sl550
x0_slc
x0_sle
x0_slk
x0_slk-class
x0_slt
x0_solara
x0_solstice
x0_sonata
x0_sonic
x0_sonoma
x0_sorento
x0_sorrento
x0_soul
x0_soul+
x0_spark
x0_spectra
x0_sport
x0_sportage
x0_sprinter
x0_srx
x0_srx-v6
x0_srx4
x0_srx~awesome
x0_ss
x0_ssr
x0_step-van
x0_stinger
x0_stratus
x0_sts
x0_suburban
x0_super
x0_supra
x0_suv
x0_svx
x0_t
x0_t-350
x0_t-bucket
x0_tacoma
x0_tahoe
x0_tarsus
x0_taurus
x0_tc5500
x0_telluride
x0_tercel
x0_terrain
x0_thing
x0_thrift
x0_thunderbird
x0_tiguan
x0_titan
x0_tl
x0_tlx
x0_torrent
x0_touareg
x0_town
x0_tracker
x0_tractor
x0_trailblazer
x0_trans
x0_transit
x0_traverse
x0_trax
x0_tribeca
x0_tribute
x0_truck
x0_tsx
x0_tt
x0_tucson
x0_tudor
x0_tundra
x0_uplander
x0_utility
x0_ux
x0_v50
x0_v6
x0_v60
x0_v90
x0_van
x0_vanagon
x0_vandura
x0_velar
x0_veloster
x0_venture
x0_venza
x0_veracruz
x0_verano
x0_versa
x0_vibe
x0_villager
x0_vnl
x0_volt
x0_voyager
x0_vtx1300c
x0_vue
x0_w350
x0_windstar
x0_wrangler
x0_wrx
x0_x-3
x0_x-type
x0_x1
x0_x2
x0_x3
x0_x4
x0_x5
x0_x6
x0_xc
x0_xc40
x0_xc60
x0_xc70
x0_xc90
x0_xe
x0_xf
x0_xj
x0_xj-series
x0_xj8
x0_xk8
x0_xt4
x0_xt5
x0_xt6
x0_xterra
x0_xts
x0_xv
x0_yaris
x0_yukon
x0_z
x0_z3
x0_z4
x0_zephyr
x0_zx2
x1_black
x1_blue
x1_brown
x1_custom
x1_green
x1_grey
x1_orange
x1_other
x1_purple
x1_red
x1_silver
x1_white
x1_yellow
x2_SUV
x2_bus
x2_convertible
x2_coupe
x2_hatchback
x2_mini-van
x2_offroad
x2_other
x2_pickup
x2_sedan
x2_truck
x2_van
x2_wagon
x3_compact
x3_full-size
x3_mid-size
x3_other
x3_sub-compact
x4_4wd
x4_fwd
x4_other
x4_rwd
x5_diesel
x5_electric
x5_gas
x5_hybrid
x5_other
x6_10 cylinders
x6_3 cylinders
x6_4 cylinders
x6_5 cylinders
x6_6 cylinders
x6_8 cylinders
x6_other
x7_SF bay area
x7_abilene
x7_akron / canton
x7_albany
x7_albuquerque
x7_altoona-johnstown
x7_amarillo
x7_ames
x7_anchorage / mat-su
x7_ann arbor
x7_annapolis
x7_appleton-oshkosh-FDL
x7_asheville
x7_ashtabula
x7_athens
x7_atlanta
x7_auburn
x7_augusta
x7_austin
x7_bakersfield
x7_baltimore
x7_baton rouge
x7_battle creek
x7_beaumont / port arthur
x7_bellingham
x7_bemidji
x7_bend
x7_billings
x7_binghamton
x7_birmingham
x7_bismarck
x7_bloomington
x7_bloomington-normal
x7_boise
x7_boone
x7_boston
x7_boulder
x7_bowling green
x7_bozeman
x7_brainerd
x7_brownsville
x7_brunswick
x7_buffalo
x7_butte
x7_cape cod / islands
x7_catskills
x7_cedar rapids
x7_central NJ
x7_central louisiana
x7_central michigan
x7_champaign urbana
x7_charleston
x7_charlotte
x7_charlottesville
x7_chattanooga
x7_chautauqua
x7_chicago
x7_chico
x7_chillicothe
x7_cincinnati
x7_clarksville
x7_cleveland
x7_clovis / portales
x7_college station
x7_colorado springs
x7_columbia
x7_columbia / jeff city
x7_columbus
x7_corpus christi
x7_corvallis/albany
x7_cumberland valley
x7_dallas / fort worth
x7_danville
x7_dayton / springfield
x7_daytona beach
x7_decatur
x7_del rio / eagle pass
x7_delaware
x7_denver
x7_des moines
x7_detroit metro
x7_dothan
x7_dubuque
x7_duluth / superior
x7_east idaho
x7_east oregon
x7_eastern CO
x7_eastern CT
x7_eastern NC
x7_eastern kentucky
x7_eastern montana
x7_eastern panhandle
x7_eastern shore
x7_eau claire
x7_el paso
x7_elko
x7_elmira-corning
x7_erie
x7_eugene
x7_evansville
x7_fairbanks
x7_fargo / moorhead
x7_farmington
x7_fayetteville
x7_finger lakes
x7_flagstaff / sedona
x7_flint
x7_florence
x7_florence / muscle shoals
x7_florida keys
x7_fort collins / north CO
x7_fort dodge
x7_fort smith
x7_fort wayne
x7_frederick
x7_fredericksburg
x7_fresno / madera
x7_ft myers / SW florida
x7_gadsden-anniston
x7_gainesville
x7_galveston
x7_glens falls
x7_gold country
x7_grand forks
x7_grand island
x7_grand rapids
x7_great falls
x7_green bay
x7_greensboro
x7_greenville / upstate
x7_gulfport / biloxi
x7_hanford-corcoran
x7_harrisburg
x7_harrisonburg
x7_hartford
x7_hattiesburg
x7_hawaii
x7_heartland florida
x7_helena
x7_hickory / lenoir
x7_high rockies
x7_hilton head
x7_holland
x7_houma
x7_houston
x7_hudson valley
x7_humboldt county
x7_huntington-ashland
x7_huntsville / decatur
x7_imperial county
x7_indianapolis
x7_inland empire
x7_iowa city
x7_ithaca
x7_jackson
x7_jacksonville
x7_janesville
x7_jersey shore
x7_jonesboro
x7_joplin
x7_kalamazoo
x7_kalispell
x7_kansas city, MO
x7_kenai peninsula
x7_kennewick-pasco-richland
x7_kenosha-racine
x7_killeen / temple / ft hood
x7_kirksville
x7_klamath falls
x7_knoxville
x7_kokomo
x7_la crosse
x7_la salle co
x7_lafayette
x7_lafayette / west lafayette
x7_lake charles
x7_lake of the ozarks
x7_lakeland
x7_lancaster
x7_lansing
x7_laredo
x7_las cruces
x7_las vegas
x7_lawrence
x7_lawton
x7_lehigh valley
x7_lewiston / clarkston
x7_lexington
x7_lima / findlay
x7_lincoln
x7_little rock
x7_logan
x7_long island
x7_los angeles
x7_louisville
x7_lubbock
x7_lynchburg
x7_macon / warner robins
x7_madison
x7_maine
x7_manhattan
x7_mankato
x7_mansfield
x7_mason city
x7_mattoon-charleston
x7_mcallen / edinburg
x7_meadville
x7_medford-ashland
x7_memphis
x7_mendocino county
x7_merced
x7_milwaukee
x7_minneapolis / st paul
x7_missoula
x7_mobile
x7_modesto
x7_mohave county
x7_monroe
x7_monterey bay
x7_montgomery
x7_morgantown
x7_moses lake
x7_muncie / anderson
x7_muskegon
x7_myrtle beach
x7_nashville
x7_new hampshire
x7_new haven
x7_new orleans
x7_new river valley
x7_new york city
x7_norfolk / hampton roads
x7_north central FL
x7_north dakota
x7_north jersey
x7_north mississippi
x7_north platte
x7_northeast SD
x7_northern WI
x7_northern michigan
x7_northern panhandle
x7_northwest CT
x7_northwest GA
x7_northwest KS
x7_northwest OK
x7_ocala
x7_odessa / midland
x7_ogden-clearfield
x7_okaloosa / walton
x7_oklahoma city
x7_olympic peninsula
x7_omaha / council bluffs
x7_oneonta
x7_orange county
x7_oregon coast
x7_orlando
x7_outer banks
x7_owensboro
x7_palm springs
x7_panama city
x7_parkersburg-marietta
x7_pensacola
x7_peoria
x7_philadelphia
x7_phoenix
x7_pierre / central SD
x7_pittsburgh
x7_plattsburgh-adirondacks
x7_poconos
x7_port huron
x7_portland
x7_potsdam-canton-massena
x7_prescott
x7_pueblo
x7_pullman / moscow
x7_quad cities, IA/IL
x7_raleigh / durham / CH
x7_rapid city / west SD
x7_reading
x7_redding
x7_reno / tahoe
x7_rhode island
x7_richmond
x7_roanoke
x7_rochester
x7_rockford
x7_roseburg
x7_roswell / carlsbad
x7_sacramento
x7_saginaw-midland-baycity
x7_salem
x7_salina
x7_salt lake city
x7_san angelo
x7_san antonio
x7_san diego
x7_san luis obispo
x7_san marcos
x7_sandusky
x7_santa barbara
x7_santa fe / taos
x7_santa maria
x7_sarasota-bradenton
x7_savannah / hinesville
x7_scottsbluff / panhandle
x7_scranton / wilkes-barre
x7_seattle-tacoma
x7_sheboygan
x7_show low
x7_shreveport
x7_sierra vista
x7_sioux city
x7_sioux falls / SE SD
x7_siskiyou county
x7_skagit / island / SJI
x7_south bend / michiana
x7_south coast
x7_south dakota
x7_south florida
x7_south jersey
x7_southeast IA
x7_southeast alaska
x7_southeast missouri
x7_southern illinois
x7_southern maryland
x7_southwest KS
x7_southwest MN
x7_southwest MS
x7_southwest VA
x7_southwest michigan
x7_space coast
x7_spokane / coeur d'alene
x7_springfield
x7_st augustine
x7_st cloud
x7_st george
x7_st joseph
x7_st louis, MO
x7_state college
x7_statesboro
x7_stillwater
x7_stockton
x7_susanville
x7_syracuse
x7_tallahassee
x7_tampa bay area
x7_terre haute
x7_texarkana
x7_texoma
x7_the thumb
x7_toledo
x7_topeka
x7_treasure coast
x7_tri-cities
x7_tucson
x7_tulsa
x7_tuscaloosa
x7_tuscarawas co
x7_twin falls
x7_twin tiers NY/PA
x7_tyler / east TX
x7_upper peninsula
x7_utica-rome-oneida
x7_valdosta
x7_ventura county
x7_vermont
x7_victoria
x7_visalia-tulare
x7_waco
x7_washington, DC
x7_waterloo / cedar falls
x7_watertown
x7_wausau
x7_wenatchee
x7_western KY
x7_western maryland
x7_western massachusetts
x7_western slope
x7_wichita
x7_wichita falls
x7_williamsport
x7_wilmington
x7_winchester
x7_winston-salem
x7_worcester / central MA
x7_wyoming
x7_yakima
x7_york
x7_youngstown
x7_yuba-sutter
x7_yuma
x7_zanesville / cambridge
x8_excellent
x8_fair
x8_good
x8_like new
x8_new
x8_salvage
x9_automatic
x9_manual
x9_other
x10_ak
x10_al
x10_ar
x10_az
x10_ca
x10_co
x10_ct
x10_dc
x10_de
x10_fl
x10_ga
x10_hi
x10_ia
x10_id
x10_il
x10_in
x10_ks
x10_ky
x10_la
x10_ma
x10_md
x10_me
x10_mi
x10_mn
x10_mo
x10_ms
x10_mt
x10_nc
x10_nd
x10_ne
x10_nh
x10_nj
x10_nm
x10_nv
x10_ny
x10_oh
x10_ok
x10_or
x10_pa
x10_ri
x10_sc
x10_sd
x10_tn
x10_tx
x10_ut
x10_va
x10_vt
x10_wa
x10_wi
x10_wv
x10_wy
x11_acura
x11_alfa-romeo
x11_audi
x11_bmw
x11_buick
x11_cadillac
x11_chevrolet
x11_chrysler
x11_datsun
x11_dodge
x11_ferrari
x11_fiat
x11_ford
x11_gmc
x11_harley-davidson
x11_honda
x11_hyundai
x11_infiniti
x11_jaguar
x11_jeep
x11_kia
x11_lexus
x11_lincoln
x11_mazda
x11_mercedes-benz
x11_mercury
x11_mini
x11_mitsubishi
x11_nissan
x11_pontiac
x11_porsche
x11_ram
x11_rover
x11_saturn
x11_subaru
x11_tesla
x11_toyota
x11_volkswagen
x11_volvo
x12_SF bay area
x12_abilene
x12_akron / canton
x12_albany
x12_albuquerque
x12_altoona-johnstown
x12_amarillo
x12_ames
x12_anchorage / mat-su
x12_ann arbor
x12_annapolis
x12_appleton-oshkosh-FDL
x12_asheville
x12_ashtabula
x12_athens
x12_atlanta
x12_auburn
x12_augusta
x12_austin
x12_bakersfield
x12_baltimore
x12_baton rouge
x12_battle creek
x12_beaumont / port arthur
x12_bellingham
x12_bemidji
x12_bend
x12_billings
x12_binghamton
x12_birmingham
x12_bismarck
x12_bloomington
x12_bloomington-normal
x12_boise
x12_boone
x12_boston
x12_boulder
x12_bowling green
x12_bozeman
x12_brainerd
x12_brownsville
x12_brunswick
x12_buffalo
x12_butte
x12_cape cod / islands
x12_catskills
x12_cedar rapids
x12_central NJ
x12_central louisiana
x12_central michigan
x12_champaign urbana
x12_charleston
x12_charlotte
x12_charlottesville
x12_chattanooga
x12_chautauqua
x12_chicago
x12_chico
x12_chillicothe
x12_cincinnati
x12_clarksville
x12_cleveland
x12_clovis / portales
x12_college station
x12_colorado springs
x12_columbia
x12_columbia / jeff city
x12_columbus
x12_corpus christi
x12_corvallis/albany
x12_cumberland valley
x12_dallas / fort worth
x12_danville
x12_dayton / springfield
x12_daytona beach
x12_decatur
x12_del rio / eagle pass
x12_delaware
x12_denver
x12_des moines
x12_detroit metro
x12_dothan
x12_dubuque
x12_duluth / superior
x12_east idaho
x12_east oregon
x12_eastern CO
x12_eastern CT
x12_eastern NC
x12_eastern kentucky
x12_eastern montana
x12_eastern panhandle
x12_eastern shore
x12_eau claire
x12_el paso
x12_elko
x12_elmira-corning
x12_erie
x12_eugene
x12_evansville
x12_fairbanks
x12_fargo / moorhead
x12_farmington
x12_fayetteville
x12_finger lakes
x12_flagstaff / sedona
x12_flint
x12_florence
x12_florence / muscle shoals
x12_florida keys
x12_fort collins / north CO
x12_fort dodge
x12_fort smith
x12_fort wayne
x12_frederick
x12_fredericksburg
x12_fresno / madera
x12_ft myers / SW florida
x12_gadsden-anniston
x12_gainesville
x12_galveston
x12_glens falls
x12_gold country
x12_grand forks
x12_grand island
x12_grand rapids
x12_great falls
x12_green bay
x12_greensboro
x12_greenville / upstate
x12_gulfport / biloxi
x12_hanford-corcoran
x12_harrisburg
x12_harrisonburg
x12_hartford
x12_hattiesburg
x12_hawaii
x12_heartland florida
x12_helena
x12_hickory / lenoir
x12_high rockies
x12_hilton head
x12_holland
x12_houma
x12_houston
x12_hudson valley
x12_humboldt county
x12_huntington-ashland
x12_huntsville / decatur
x12_imperial county
x12_indianapolis
x12_inland empire
x12_iowa city
x12_ithaca
x12_jackson
x12_jacksonville
x12_janesville
x12_jersey shore
x12_jonesboro
x12_joplin
x12_kalamazoo
x12_kalispell
x12_kansas city, MO
x12_kenai peninsula
x12_kennewick-pasco-richland
x12_kenosha-racine
x12_killeen / temple / ft hood
x12_kirksville
x12_klamath falls
x12_knoxville
x12_kokomo
x12_la crosse
x12_la salle co
x12_lafayette
x12_lafayette / west lafayette
x12_lake charles
x12_lake of the ozarks
x12_lakeland
x12_lancaster
x12_lansing
x12_laredo
x12_las cruces
x12_las vegas
x12_lawrence
x12_lawton
x12_lehigh valley
x12_lewiston / clarkston
x12_lexington
x12_lima / findlay
x12_lincoln
x12_little rock
x12_logan
x12_long island
x12_los angeles
x12_louisville
x12_lubbock
x12_lynchburg
x12_macon / warner robins
x12_madison
x12_maine
x12_manhattan
x12_mankato
x12_mansfield
x12_mason city
x12_mattoon-charleston
x12_mcallen / edinburg
x12_meadville
x12_medford-ashland
x12_memphis
x12_mendocino county
x12_merced
x12_milwaukee
x12_minneapolis / st paul
x12_missoula
x12_mobile
x12_modesto
x12_mohave county
x12_monroe
x12_monterey bay
x12_montgomery
x12_morgantown
x12_moses lake
x12_muncie / anderson
x12_muskegon
x12_myrtle beach
x12_nashville
x12_new hampshire
x12_new haven
x12_new orleans
x12_new river valley
x12_new york city
x12_norfolk / hampton roads
x12_north central FL
x12_north dakota
x12_north jersey
x12_north mississippi
x12_north platte
x12_northeast SD
x12_northern WI
x12_northern michigan
x12_northern panhandle
x12_northwest CT
x12_northwest GA
x12_northwest KS
x12_northwest OK
x12_ocala
x12_odessa / midland
x12_ogden-clearfield
x12_okaloosa / walton
x12_oklahoma city
x12_olympic peninsula
x12_omaha / council bluffs
x12_oneonta
x12_orange county
x12_oregon coast
x12_orlando
x12_outer banks
x12_owensboro
x12_palm springs
x12_panama city
x12_parkersburg-marietta
x12_pensacola
x12_peoria
x12_philadelphia
x12_phoenix
x12_pierre / central SD
x12_pittsburgh
x12_plattsburgh-adirondacks
x12_poconos
x12_port huron
x12_portland
x12_potsdam-canton-massena
x12_prescott
x12_pueblo
x12_pullman / moscow
x12_quad cities, IA/IL
x12_raleigh / durham / CH
x12_rapid city / west SD
x12_reading
x12_redding
x12_reno / tahoe
x12_rhode island
x12_richmond
x12_roanoke
x12_rochester
x12_rockford
x12_roseburg
x12_roswell / carlsbad
x12_sacramento
x12_saginaw-midland-baycity
x12_salem
x12_salina
x12_salt lake city
x12_san angelo
x12_san antonio
x12_san diego
x12_san luis obispo
x12_san marcos
x12_sandusky
x12_santa barbara
x12_santa fe / taos
x12_santa maria
x12_sarasota-bradenton
x12_savannah / hinesville
x12_scottsbluff / panhandle
x12_scranton / wilkes-barre
x12_seattle-tacoma
x12_sheboygan

## Нормализуем количественные переменные

In [146]:
#Создадим дополнительные колонки для количественных переменных
df['desc_len'] = df.apply(lambda x: len(x.description), axis=1)   
df['model_in_desc'] = df.apply(lambda x: x.description.count(x.short_model), axis=1)

In [147]:
#И отдельный датафрем для количественных переменных
data_std = df[['year', 'odometer', 'desc_len', 'model_in_desc', 'lat', 'long']]
data_std.head()

     year  odometer  desc_len  model_in_desc        lat       long
0  2020.0   27442.0      4482             14  35.060000 -85.250000
2  2017.0   14048.0      4286              0  33.779214 -84.411811
3  2013.0  117291.0      3241              0  35.715954 -78.655304
4  2021.0    8000.0       538              0  40.654800 -73.609700
5  2012.0   80465.0      4851            114  35.970000 -83.940000

In [148]:
std_scaler = StandardScaler()
std_scaler

StandardScaler()

In [149]:
# Идентифицируем параметры преобразования на датафрейме с количественными переменными.
std_scaler.fit(data_std[['year', 'odometer', 'desc_len', 'model_in_desc', 'lat', 'long']])

StandardScaler()

In [150]:
#Примениv преобразование для датафрейма с количественными переменными и сохраниv в новую переменную.
std_scaled = std_scaler.transform(data_std[['year', 'odometer', 'desc_len', 'model_in_desc', 'lat', 'long']])
std_scaled

array([[ 1.29323937, -1.0500037 ,  0.60663788,  0.95796691, -0.60777326,
         0.49239246],
       [ 0.81931022, -1.2628773 ,  0.53612463, -0.13600173, -0.82666348,
         0.53873452],
       [ 0.18740467,  0.37798495,  0.16017389, -0.13600173, -0.49566873,
         0.85700216],
       ...,
       [-0.1285481 ,  0.90076017, -0.67878985, -0.13600173,  1.07834035,
        -1.59378832],
       [ 0.50335744, -0.5016722 ,  0.30515777, -0.13600173,  0.75424855,
         0.26306776],
       [ 0.81931022, -0.91524521,  0.60699764,  1.11424814, -0.33261938,
         0.98722298]])

In [151]:
#Создадим новые стандартизированные признаки
data_std[['year_std', 'odometer_std', 'desc_len_std', 'model_in_desc_std', 'lat_std', 'long_std']] = std_scaled
data_std.head()

J:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3678: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[col] = igetitem(value, i)

,year,odometer,desc_len,model_in_desc,lat,long,year_std,odometer_std,desc_len_std,model_in_desc_std,lat_std,long_std
0,2020.0,27442.0,4482,14,35.060000,-85.250000,1.293239,-1.050004,0.606638,0.957967,-0.607773,0.492392
2,2017.0,14048.0,4286,0,33.779214,-84.411811,0.819310,-1.262877,0.536125,-0.136002,-0.826663,0.538735
3,2013.0,117291.0,3241,0,35.715954,-78.655304,0.187405,0.377985,0.160174,-0.136002,-0.495669,0.857002
4,2021.0,8000.0,538,0,40.654800,-73.609700,1.451216,-1.358999,-0.812261,-0.136002,0.348395,1.135965
5,2012.0,80465.0,4851,114,35.970000,-83.940000,0.029428,-0.207298,0.739390,8.772029,-0.452252,0.564820

In [152]:
#Добавим новын признаки в рабочий датафрейм
df_ohe_1[['year_std', 'odometer_std', 'desc_len_std', 'model_in_desc_std', 'lat_std', 'long_std']] = std_scaled
df_ohe_1.head()

,price,year,odometer,description,lat,long,posting_date,price_category,x0_-benz,x0_1,...,x13_missing,x13_parts only,x13_rebuilt,x13_salvage,year_std,odometer_std,desc_len_std,model_in_desc_std,lat_std,long_std
0,54990,2020.0,27442.0,Carvana is the safer way to buy a car During t...,35.060000,-85.250000,2021-04-17T12:30:50-0400,high,0.0,0.0,...,0.0,0.0,0.0,0.0,1.293239,-1.050004,0.606638,0.957967,-0.607773,0.492392
2,35590,2017.0,14048.0,Carvana is the safer way to buy a car During t...,33.779214,-84.411811,2021-04-28T03:52:20-0700,high,0.0,0.0,...,0.0,0.0,0.0,0.0,0.819310,-1.262877,0.536125,-0.136002,-0.826663,0.538735
3,14500,2013.0,117291.0,2013 Toyota RAV4 XLE 4dr SUV Offered by: R...,35.715954,-78.655304,2021-04-17T10:08:57-0400,medium,0.0,0.0,...,0.0,0.0,0.0,0.0,0.187405,0.377985,0.160174,-0.136002,-0.495669,0.857002
4,21800,2021.0,8000.0,2021 Nissan Altima Sv with Only 8 K Miles Titl...,40.654800,-73.609700,2021-05-03T18:32:06-0400,medium,0.0,0.0,...,0.0,0.0,0.0,0.0,1.451216,-1.358999,-0.812261,-0.136002,0.348395,1.135965
5,14590,2012.0,80465.0,Carvana is the safer way to buy a car During t...,35.970000,-83.940000,2021-04-08T15:10:56-0400,medium,0.0,1.0,...,0.0,0.0,0.0,0.0,0.029428,-0.207298,0.739390,8.772029,-0.452252,0.564820

### Стандартизация переменной в формате даты

In [153]:
# У нас только одна переменная в формате даты - posting_date
df_ohe_1.posting_date

0        2021-04-17T12:30:50-0400
2        2021-04-28T03:52:20-0700
3        2021-04-17T10:08:57-0400
4        2021-05-03T18:32:06-0400
5        2021-04-08T15:10:56-0400
                   ...
10045    2021-04-10T16:33:57-0400
10046    2021-05-03T09:36:30-0400
10047    2021-04-22T12:14:01-0700
10048    2021-04-14T09:14:42-0500
10049    2021-04-24T13:50:49-0400
Name: posting_date, Length: 9448, dtype: object

In [154]:
# Поменяем тип на datetime
df_ohe_1['posting_date'] = pd.to_datetime(df_ohe_1.posting_date, utc=True)
df_ohe_1.posting_date

0       2021-04-17 16:30:50+00:00
2       2021-04-28 10:52:20+00:00
3       2021-04-17 14:08:57+00:00
4       2021-05-03 22:32:06+00:00
5       2021-04-08 19:10:56+00:00
                   ...
10045   2021-04-10 20:33:57+00:00
10046   2021-05-03 13:36:30+00:00
10047   2021-04-22 19:14:01+00:00
10048   2021-04-14 14:14:42+00:00
10049   2021-04-24 17:50:49+00:00
Name: posting_date, Length: 9448, dtype: datetime64[ns, UTC]

In [155]:
#День значения не имеет, а год и месяц могут влиять на результат.
#Создадим две дополнительные фичи: diff_year - разница между годом публикации и годом выпуска автомобиля, и month - месяц публицации
df_ohe_1['month'] = df_ohe_1.posting_date.dt.month
df_ohe_1['diff_years'] = df_ohe_1.apply(lambda x: x.posting_date.year - x.year, axis=1)

In [156]:
#Применим стандартизацию к новым признаками
std_scaler.fit(df_ohe_1[['month', 'diff_years']])
std_scaled = std_scaler.transform(df_ohe_1[['month', 'diff_years']])
df_ohe_1[['month_std', 'diff_years_std']] = std_scaled

In [157]:
#Финальный датасет
columns_for_drop = ['year', 'posting_date', 'month', 'diff_years', 'odometer', 'description', 'lat', 'long']
df_prepared = df_ohe_1.drop(columns_for_drop, axis=1)

In [158]:
df_prepared.head()

,price,price_category,x0_-benz,x0_1,x0_124,x0_128i,x0_135i,x0_1500,x0_2,x0_200,...,x13_rebuilt,x13_salvage,year_std,odometer_std,desc_len_std,model_in_desc_std,lat_std,long_std,month_std,diff_years_std
0,54990,high,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.293239,-1.050004,0.606638,0.957967,-0.607773,0.492392,-0.615359,-1.293239
2,35590,high,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.819310,-1.262877,0.536125,-0.136002,-0.826663,0.538735,-0.615359,-0.819310
3,14500,medium,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.187405,0.377985,0.160174,-0.136002,-0.495669,0.857002,-0.615359,-0.187405
4,21800,medium,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.451216,-1.358999,-0.812261,-0.136002,0.348395,1.135965,1.625069,-1.451216
5,14590,medium,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.029428,-0.207298,0.739390,8.772029,-0.452252,0.564820,-0.615359,-0.029428

In [159]:
df_prepared.to_csv('data/vehicles_dataset_prepared.csv', index=False)

In [160]:
col = df_prepared.columns
for i in col:
    print(i)

price
price_category
x0_-benz
x0_1
x0_124
x0_128i
x0_135i
x0_1500
x0_2
x0_200
x0_2018
x0_210
x0_240
x0_2500
x0_2500hd
x0_280zx
x0_3
x0_3-series
x0_3-window
x0_3.2
x0_300
x0_300-series
x0_300c
x0_300s
x0_300zx
x0_3100
x0_318i
x0_320i
x0_323i
x0_325ci
x0_325i
x0_325is
x0_325xi
x0_328
x0_328ci
x0_328d
x0_328i
x0_328xi
x0_330i
x0_330xi
x0_335i
x0_335xi
x0_350
x0_3500
x0_3500hd
x0_350z
x0_370z
x0_380sl
x0_3i
x0_4
x0_4-runner
x0_428
x0_430i
x0_435i
x0_440xi
x0_4500
x0_488
x0_4runner
x0_4x4
x0_5
x0_5-series
x0_50
x0_500
x0_500c
x0_500l
x0_500x
x0_525i
x0_528i
x0_528xi
x0_530
x0_530i
x0_535i
x0_535xi
x0_540i
x0_545i
x0_5500
x0_5500hd
x0_550i
x0_5th
x0_6
x0_640
x0_645ci
x0_650i
x0_650xi
x0_7
x0_750
x0_750i
x0_750xi
x0_86
x0_911
x0_914
x0_928
x0_944
x0_a-class
x0_a3
x0_a3,
x0_a4
x0_a5
x0_a6
x0_a7
x0_a8
x0_acadia
x0_accent
x0_accord
x0_allante
x0_allroad
x0_altima
x0_arcadia
x0_armada
x0_arteon
x0_ascent
x0_aspen
x0_astra
x0_astro
x0_atlas
x0_ats
x0_aura
x0_autobiography
x0_avalanche
x0_avalon
x0_avanger
x0_avenger
x0_aveo
x0_aviator
x0_azera
x0_aztek
x0_b-class
x0_b-series
x0_b2200
x0_b2300
x0_b2600i
x0_baja
x0_beetle
x0_bel
x0_belair
x0_benz
x0_blackwood
x0_blazer
x0_bolt
x0_bonanza
x0_bonneville
x0_boxster
x0_bronco
x0_brz
x0_bug
x0_bus
x0_c
x0_c-10
x0_c-class
x0_c-hr
x0_c-max
x0_c/k
x0_c10
x0_c250
x0_c280
x0_c300
x0_c4500
x0_c5500
x0_c60
x0_c6500
x0_c70
x0_c8500
x0_cabellero
x0_cabrio
x0_cadenza
x0_caliber
x0_camaro
x0_camary
x0_camero
x0_camry
x0_canyon
x0_capri
x0_caprice
x0_captiva
x0_caravan
x0_caravan/grand
x0_cargo
x0_cascada
x0_cavalier
x0_cayenne
x0_cayman
x0_cc
x0_cc4500
x0_century
x0_certified
x0_challenger
x0_charger
x0_cherokee
x0_chevelle
x0_city
x0_civic
x0_cj-5
x0_cj2a
x0_cj5
x0_cj7
x0_cj8
x0_cl-class
x0_cla
x0_cla-class
x0_clarity
x0_classic
x0_classuc
x0_clk
x0_clk-class
x0_clk350
x0_cls-class
x0_cls550
x0_clubman
x0_cmax
x0_cobalt
x0_coe
x0_colbalt
x0_colorado
x0_comet
x0_commander
x0_compass
x0_concorde
x0_conquest
x0_continental
x0_convertible
x0_cooper
x0_corolla
x0_corsair
x0_corvette
x0_cougar
x0_country
x0_countryman
x0_coupe
x0_cr-v
x0_crew
x0_crossfire
x0_crosstour
x0_crosstrek
x0_crown
x0_cruze
x0_crv
x0_crz
x0_ct
x0_ct4
x0_ct5
x0_ct6
x0_cts
x0_cts4
x0_cube
x0_cummins
x0_cvr
x0_cx-3
x0_cx-5
x0_cx-7
x0_cx-9
x0_cx7
x0_cx9
x0_d50
x0_dakota
x0_dart
x0_davidson
x0_dealer*
x0_defender
x0_deisel
x0_deluxe
x0_denali
x0_deville
x0_diesel
x0_discovery
x0_dts
x0_dump
x0_duramax
x0_durango
x0_durangon
x0_e
x0_e-150
x0_e-250
x0_e-350
x0_e-450
x0_e-class
x0_e-golf
x0_e-pace
x0_e-series
x0_e150
x0_e250
x0_e320
x0_e350
x0_e450
x0_e46
x0_e500
x0_echo
x0_eclipse
x0_econoline
x0_ecosport
x0_edge
x0_el
x0_elantra
x0_elcamino
x0_eldorado
x0_element
x0_enclave
x0_encore
x0_endeavor
x0_envision
x0_envoy
x0_eos
x0_eqinox
x0_equinox
x0_es
x0_es300
x0_es330
x0_es350
x0_escalade
x0_escape
x0_escape-se,
x0_escort
x0_eurovan
x0_evoque
x0_excursion
x0_expedition
x0_explorer
x0_express
x0_f
x0_f-100
x0_f-150
x0_f-250
x0_f-250sd
x0_f-350
x0_f-350sd
x0_f-450
x0_f-450sd
x0_f-550
x0_f-550sd
x0_f-650
x0_f-750
x0_f-pace
x0_f-type
x0_f1
x0_f100
x0_f150
x0_f250
x0_f350
x0_f430
x0_f450
x0_f450sd
x0_f50
x0_f550
x0_f600
x0_f650
x0_f700
x0_f750
x0_falcon
x0_fe
x0_fiero
x0_fiesta
x0_firebird
x0_fit
x0_five
x0_fj
x0_fj40
x0_fleetmaster
x0_fleetwood
x0_flex
x0_focus
x0_forester
x0_forte
x0_forte5
x0_foxbody
x0_freestar
x0_freestyle
x0_frontier
x0_fusion
x0_fuso
x0_fx35
x0_fx45
x0_g
x0_g-class
x0_g.
x0_g20
x0_g30
x0_g35
x0_g35x
x0_g37
x0_g37s
x0_g37x
x0_g4500
x0_g5
x0_g6
x0_g8
x0_galant
x0_genesis
x0_ghia
x0_gl
x0_gl-class
x0_gl450
x0_gla
x0_gla-class
x0_gladiator
x0_glc
x0_glc-class
x0_gle
x0_gle-class
x0_glk
x0_glk-class
x0_glk350
x0_gls
x0_gmt-400
x0_golf
x0_gr
x0_grand
x0_grandville
x0_grumman
x0_gs
x0_gs350
x0_gs430
x0_gt
x0_gt-r
x0_gti
x0_gto
x0_gx
x0_gx460
x0_gx470
x0_hardbody
x0_hardtop
x0_hearse
x0_hhr
x0_hiace
x0_high
x0_highlander
x0_hr-v
x0_hse
x0_i-miev
x0_i3
x0_i30
x0_i35
x0_i8
x0_ilx
x0_impala
x0_impreza
x0_insight
x0_ion
x0_ioniq
x0_is
x0_is250
x0_is300
x0_isf
x0_jetta
x0_jimmy
x0_jouney
x0_journey
x0_juke
x0_jx35
x0_k10
x0_k20
x0_k30
x0_k5
x0_k900
x0_kicks
x0_kodiak
x0_l
x0_l300
x0_lacrosse
x0_lancer
x0_land
x0_landcruiser
x0_leaf
x0_legacy
x0_legend
x0_lemans
x0_lesabre
x0_liberty
x0_lifted
x0_lightning
x0_limousine
x0_long
x0_lr2
x0_lr3
x0_lr4
x0_ls
x0_ltd
x0_lucerne
x0_lx
x0_lx450
x0_m
x0_m-class
x0_m3
x0_m35
x0_m35s
x0_m4
x0_m5
x0_macan
x0_magnum
x0_malibu
x0_mallinia
x0_marineer,premier
x0_mariner
x0_mark
x0_matrix
x0_maxima
x0_maximum
x0_maybach
x0_mazda2
x0_mazda3
x0_mazda5
x0_mazda6
x0_mazda6i
x0_md-x
x0_mdx
x0_mercedes-amg
x0_metris
x0_miata
x0_mighty
x0_milan
x0_mirage
x0_mkc
x0_mks
x0_mkt
x0_mkx
x0_mkz
x0_ml
x0_ml350
x0_ml500
x0_model
x0_monte
x0_montero
x0_mountaineer
x0_mpv
x0_mr2
x0_murano
x0_mustang
x0_mx-5
x0_nautilus
x0_navigator
x0_neon
x0_new
x0_newport
x0_niro
x0_nitro
x0_nova
x0_nv
x0_nv1500
x0_nv200
x0_nv2500
x0_nv2500hd
x0_nx
x0_nx300
x0_oddyssey
x0_odyssey
x0_optima
x0_optimia
x0_other
x0_outback
x0_outlander
x0_outlook
x0_paceman
x0_pacifica
x0_panamera
x0_panel
x0_park
x0_passat
x0_passport
x0_pathfinder
x0_patriot
x0_phaeton
x0_pick
x0_pickup
x0_pilot
x0_prelude
x0_prius
x0_prizm
x0_promaster
x0_protege
x0_pt
x0_putback
x0_q3
x0_q5
x0_q50
x0_q60
x0_q7
x0_q70
x0_q8
x0_quattro
x0_quest
x0_qx50
x0_qx56
x0_qx60
x0_qx70
x0_qx80
x0_r-class
x0_r32
x0_rabbit
x0_rainier
x0_ram1500
x0_ramcharger
x0_range
x0_ranger
x0_rat
x0_rav
x0_rav4
x0_rc
x0_rdx
x0_reatta
x0_rebel
x0_regal
x0_rendezvous
x0_renegade
x0_replica
x0_ridgeline
x0_rio
x0_rivera
x0_riviera
x0_rl
x0_rlx
x0_roadmaster
x0_roadster
x0_rogue
x0_romeo
x0_rondo
x0_rouge
x0_routan
x0_rs
x0_rsx
x0_rx
x0_rx-8
x0_rx300
x0_rx330
x0_rx350
x0_rx400h
x0_rx7
x0_rx8
x0_s
x0_s-class
x0_s/w
x0_s10
x0_s2000
x0_s3
x0_s320
x0_s4
x0_s40
x0_s430
x0_s5
x0_s500
x0_s6
x0_s60
x0_s7
x0_s70
x0_s8
x0_s90
x0_sable
x0_santa
x0_sante
x0_savana
x0_sc
x0_sc2
x0_sc300
x0_school
x0_scion
x0_sebring
x0_sedan
x0_sedona
x0_seirra
x0_sentra
x0_sequioa
x0_sequoia
x0_seville
x0_sienna
x0_sierra
x0_sierra1500
x0_silverado
x0_sky
x0_skylark
x0_sl-class
x0_sl2
x0_sl500
x0_sl55
x0_sl550
x0_slc
x0_sle
x0_slk
x0_slk-class
x0_slt
x0_solara
x0_solstice
x0_sonata
x0_sonic
x0_sonoma
x0_sorento
x0_sorrento
x0_soul
x0_soul+
x0_spark
x0_spectra
x0_sport
x0_sportage
x0_sprinter
x0_srx
x0_srx-v6
x0_srx4
x0_srx~awesome
x0_ss
x0_ssr
x0_step-van
x0_stinger
x0_stratus
x0_sts
x0_suburban
x0_super
x0_supra
x0_suv
x0_svx
x0_t
x0_t-350
x0_t-bucket
x0_tacoma
x0_tahoe
x0_tarsus
x0_taurus
x0_tc5500
x0_telluride
x0_tercel
x0_terrain
x0_thing
x0_thrift
x0_thunderbird
x0_tiguan
x0_titan
x0_tl
x0_tlx
x0_torrent
x0_touareg
x0_town
x0_tracker
x0_tractor
x0_trailblazer
x0_trans
x0_transit
x0_traverse
x0_trax
x0_tribeca
x0_tribute
x0_truck
x0_tsx
x0_tt
x0_tucson
x0_tudor
x0_tundra
x0_uplander
x0_utility
x0_ux
x0_v50
x0_v6
x0_v60
x0_v90
x0_van
x0_vanagon
x0_vandura
x0_velar
x0_veloster
x0_venture
x0_venza
x0_veracruz
x0_verano
x0_versa
x0_vibe
x0_villager
x0_vnl
x0_volt
x0_voyager
x0_vtx1300c
x0_vue
x0_w350
x0_windstar
x0_wrangler
x0_wrx
x0_x-3
x0_x-type
x0_x1
x0_x2
x0_x3
x0_x4
x0_x5
x0_x6
x0_xc
x0_xc40
x0_xc60
x0_xc70
x0_xc90
x0_xe
x0_xf
x0_xj
x0_xj-series
x0_xj8
x0_xk8
x0_xt4
x0_xt5
x0_xt6
x0_xterra
x0_xts
x0_xv
x0_yaris
x0_yukon
x0_z
x0_z3
x0_z4
x0_zephyr
x0_zx2
x1_black
x1_blue
x1_brown
x1_custom
x1_green
x1_grey
x1_orange
x1_other
x1_purple
x1_red
x1_silver
x1_white
x1_yellow
x2_SUV
x2_bus
x2_convertible
x2_coupe
x2_hatchback
x2_mini-van
x2_offroad
x2_other
x2_pickup
x2_sedan
x2_truck
x2_van
x2_wagon
x3_compact
x3_full-size
x3_mid-size
x3_other
x3_sub-compact
x4_4wd
x4_fwd
x4_other
x4_rwd
x5_diesel
x5_electric
x5_gas
x5_hybrid
x5_other
x6_10 cylinders
x6_3 cylinders
x6_4 cylinders
x6_5 cylinders
x6_6 cylinders
x6_8 cylinders
x6_other
x7_SF bay area
x7_abilene
x7_akron / canton
x7_albany
x7_albuquerque
x7_altoona-johnstown
x7_amarillo
x7_ames
x7_anchorage / mat-su
x7_ann arbor
x7_annapolis
x7_appleton-oshkosh-FDL
x7_asheville
x7_ashtabula
x7_athens
x7_atlanta
x7_auburn
x7_augusta
x7_austin
x7_bakersfield
x7_baltimore
x7_baton rouge
x7_battle creek
x7_beaumont / port arthur
x7_bellingham
x7_bemidji
x7_bend
x7_billings
x7_binghamton
x7_birmingham
x7_bismarck
x7_bloomington
x7_bloomington-normal
x7_boise
x7_boone
x7_boston
x7_boulder
x7_bowling green
x7_bozeman
x7_brainerd
x7_brownsville
x7_brunswick
x7_buffalo
x7_butte
x7_cape cod / islands
x7_catskills
x7_cedar rapids
x7_central NJ
x7_central louisiana
x7_central michigan
x7_champaign urbana
x7_charleston
x7_charlotte
x7_charlottesville
x7_chattanooga
x7_chautauqua
x7_chicago
x7_chico
x7_chillicothe
x7_cincinnati
x7_clarksville
x7_cleveland
x7_clovis / portales
x7_college station
x7_colorado springs
x7_columbia
x7_columbia / jeff city
x7_columbus
x7_corpus christi
x7_corvallis/albany
x7_cumberland valley
x7_dallas / fort worth
x7_danville
x7_dayton / springfield
x7_daytona beach
x7_decatur
x7_del rio / eagle pass
x7_delaware
x7_denver
x7_des moines
x7_detroit metro
x7_dothan
x7_dubuque
x7_duluth / superior
x7_east idaho
x7_east oregon
x7_eastern CO
x7_eastern CT
x7_eastern NC
x7_eastern kentucky
x7_eastern montana
x7_eastern panhandle
x7_eastern shore
x7_eau claire
x7_el paso
x7_elko
x7_elmira-corning
x7_erie
x7_eugene
x7_evansville
x7_fairbanks
x7_fargo / moorhead
x7_farmington
x7_fayetteville
x7_finger lakes
x7_flagstaff / sedona
x7_flint
x7_florence
x7_florence / muscle shoals
x7_florida keys
x7_fort collins / north CO
x7_fort dodge
x7_fort smith
x7_fort wayne
x7_frederick
x7_fredericksburg
x7_fresno / madera
x7_ft myers / SW florida
x7_gadsden-anniston
x7_gainesville
x7_galveston
x7_glens falls
x7_gold country
x7_grand forks
x7_grand island
x7_grand rapids
x7_great falls
x7_green bay
x7_greensboro
x7_greenville / upstate
x7_gulfport / biloxi
x7_hanford-corcoran
x7_harrisburg
x7_harrisonburg
x7_hartford
x7_hattiesburg
x7_hawaii
x7_heartland florida
x7_helena
x7_hickory / lenoir
x7_high rockies
x7_hilton head
x7_holland
x7_houma
x7_houston
x7_hudson valley
x7_humboldt county
x7_huntington-ashland
x7_huntsville / decatur
x7_imperial county
x7_indianapolis
x7_inland empire
x7_iowa city
x7_ithaca
x7_jackson
x7_jacksonville
x7_janesville
x7_jersey shore
x7_jonesboro
x7_joplin
x7_kalamazoo
x7_kalispell
x7_kansas city, MO
x7_kenai peninsula
x7_kennewick-pasco-richland
x7_kenosha-racine
x7_killeen / temple / ft hood
x7_kirksville
x7_klamath falls
x7_knoxville
x7_kokomo
x7_la crosse
x7_la salle co
x7_lafayette
x7_lafayette / west lafayette
x7_lake charles
x7_lake of the ozarks
x7_lakeland
x7_lancaster
x7_lansing
x7_laredo
x7_las cruces
x7_las vegas
x7_lawrence
x7_lawton
x7_lehigh valley
x7_lewiston / clarkston
x7_lexington
x7_lima / findlay
x7_lincoln
x7_little rock
x7_logan
x7_long island
x7_los angeles
x7_louisville
x7_lubbock
x7_lynchburg
x7_macon / warner robins
x7_madison
x7_maine
x7_manhattan
x7_mankato
x7_mansfield
x7_mason city
x7_mattoon-charleston
x7_mcallen / edinburg
x7_meadville
x7_medford-ashland
x7_memphis
x7_mendocino county
x7_merced
x7_milwaukee
x7_minneapolis / st paul
x7_missoula
x7_mobile
x7_modesto
x7_mohave county
x7_monroe
x7_monterey bay
x7_montgomery
x7_morgantown
x7_moses lake
x7_muncie / anderson
x7_muskegon
x7_myrtle beach
x7_nashville
x7_new hampshire
x7_new haven
x7_new orleans
x7_new river valley
x7_new york city
x7_norfolk / hampton roads
x7_north central FL
x7_north dakota
x7_north jersey
x7_north mississippi
x7_north platte
x7_northeast SD
x7_northern WI
x7_northern michigan
x7_northern panhandle
x7_northwest CT
x7_northwest GA
x7_northwest KS
x7_northwest OK
x7_ocala
x7_odessa / midland
x7_ogden-clearfield
x7_okaloosa / walton
x7_oklahoma city
x7_olympic peninsula
x7_omaha / council bluffs
x7_oneonta
x7_orange county
x7_oregon coast
x7_orlando
x7_outer banks
x7_owensboro
x7_palm springs
x7_panama city
x7_parkersburg-marietta
x7_pensacola
x7_peoria
x7_philadelphia
x7_phoenix
x7_pierre / central SD
x7_pittsburgh
x7_plattsburgh-adirondacks
x7_poconos
x7_port huron
x7_portland
x7_potsdam-canton-massena
x7_prescott
x7_pueblo
x7_pullman / moscow
x7_quad cities, IA/IL
x7_raleigh / durham / CH
x7_rapid city / west SD
x7_reading
x7_redding
x7_reno / tahoe
x7_rhode island
x7_richmond
x7_roanoke
x7_rochester
x7_rockford
x7_roseburg
x7_roswell / carlsbad
x7_sacramento
x7_saginaw-midland-baycity
x7_salem
x7_salina
x7_salt lake city
x7_san angelo
x7_san antonio
x7_san diego
x7_san luis obispo
x7_san marcos
x7_sandusky
x7_santa barbara
x7_santa fe / taos
x7_santa maria
x7_sarasota-bradenton
x7_savannah / hinesville
x7_scottsbluff / panhandle
x7_scranton / wilkes-barre
x7_seattle-tacoma
x7_sheboygan
x7_show low
x7_shreveport
x7_sierra vista
x7_sioux city
x7_sioux falls / SE SD
x7_siskiyou county
x7_skagit / island / SJI
x7_south bend / michiana
x7_south coast
x7_south dakota
x7_south florida
x7_south jersey
x7_southeast IA
x7_southeast alaska
x7_southeast missouri
x7_southern illinois
x7_southern maryland
x7_southwest KS
x7_southwest MN
x7_southwest MS
x7_southwest VA
x7_southwest michigan
x7_space coast
x7_spokane / coeur d'alene
x7_springfield
x7_st augustine
x7_st cloud
x7_st george
x7_st joseph
x7_st louis, MO
x7_state college
x7_statesboro
x7_stillwater
x7_stockton
x7_susanville
x7_syracuse
x7_tallahassee
x7_tampa bay area
x7_terre haute
x7_texarkana
x7_texoma
x7_the thumb
x7_toledo
x7_topeka
x7_treasure coast
x7_tri-cities
x7_tucson
x7_tulsa
x7_tuscaloosa
x7_tuscarawas co
x7_twin falls
x7_twin tiers NY/PA
x7_tyler / east TX
x7_upper peninsula
x7_utica-rome-oneida
x7_valdosta
x7_ventura county
x7_vermont
x7_victoria
x7_visalia-tulare
x7_waco
x7_washington, DC
x7_waterloo / cedar falls
x7_watertown
x7_wausau
x7_wenatchee
x7_western KY
x7_western maryland
x7_western massachusetts
x7_western slope
x7_wichita
x7_wichita falls
x7_williamsport
x7_wilmington
x7_winchester
x7_winston-salem
x7_worcester / central MA
x7_wyoming
x7_yakima
x7_york
x7_youngstown
x7_yuba-sutter
x7_yuma
x7_zanesville / cambridge
x8_excellent
x8_fair
x8_good
x8_like new
x8_new
x8_salvage
x9_automatic
x9_manual
x9_other
x10_ak
x10_al
x10_ar
x10_az
x10_ca
x10_co
x10_ct
x10_dc
x10_de
x10_fl
x10_ga
x10_hi
x10_ia
x10_id
x10_il
x10_in
x10_ks
x10_ky
x10_la
x10_ma
x10_md
x10_me
x10_mi
x10_mn
x10_mo
x10_ms
x10_mt
x10_nc
x10_nd
x10_ne
x10_nh
x10_nj
x10_nm
x10_nv
x10_ny
x10_oh
x10_ok
x10_or
x10_pa
x10_ri
x10_sc
x10_sd
x10_tn
x10_tx
x10_ut
x10_va
x10_vt
x10_wa
x10_wi
x10_wv
x10_wy
x11_acura
x11_alfa-romeo
x11_audi
x11_bmw
x11_buick
x11_cadillac
x11_chevrolet
x11_chrysler
x11_datsun
x11_dodge
x11_ferrari
x11_fiat
x11_ford
x11_gmc
x11_harley-davidson
x11_honda
x11_hyundai
x11_infiniti
x11_jaguar
x11_jeep
x11_kia
x11_lexus
x11_lincoln
x11_mazda
x11_mercedes-benz
x11_mercury
x11_mini
x11_mitsubishi
x11_nissan
x11_pontiac
x11_porsche
x11_ram
x11_rover
x11_saturn
x11_subaru
x11_tesla
x11_toyota
x11_volkswagen
x11_volvo
x12_SF bay area
x12_abilene
x12_akron / canton
x12_albany
x12_albuquerque
x12_altoona-johnstown
x12_amarillo
x12_ames
x12_anchorage / mat-su
x12_ann arbor
x12_annapolis
x12_appleton-oshkosh-FDL
x12_asheville
x12_ashtabula
x12_athens
x12_atlanta
x12_auburn
x12_augusta
x12_austin
x12_bakersfield
x12_baltimore
x12_baton rouge
x12_battle creek
x12_beaumont / port arthur
x12_bellingham
x12_bemidji
x12_bend
x12_billings
x12_binghamton
x12_birmingham
x12_bismarck
x12_bloomington
x12_bloomington-normal
x12_boise
x12_boone
x12_boston
x12_boulder
x12_bowling green
x12_bozeman
x12_brainerd
x12_brownsville
x12_brunswick
x12_buffalo
x12_butte
x12_cape cod / islands
x12_catskills
x12_cedar rapids
x12_central NJ
x12_central louisiana
x12_central michigan
x12_champaign urbana
x12_charleston
x12_charlotte
x12_charlottesville
x12_chattanooga
x12_chautauqua
x12_chicago
x12_chico
x12_chillicothe
x12_cincinnati
x12_clarksville
x12_cleveland
x12_clovis / portales
x12_college station
x12_colorado springs
x12_columbia
x12_columbia / jeff city
x12_columbus
x12_corpus christi
x12_corvallis/albany
x12_cumberland valley
x12_dallas / fort worth
x12_danville
x12_dayton / springfield
x12_daytona beach
x12_decatur
x12_del rio / eagle pass
x12_delaware
x12_denver
x12_des moines
x12_detroit metro
x12_dothan
x12_dubuque
x12_duluth / superior
x12_east idaho
x12_east oregon
x12_eastern CO
x12_eastern CT
x12_eastern NC
x12_eastern kentucky
x12_eastern montana
x12_eastern panhandle
x12_eastern shore
x12_eau claire
x12_el paso
x12_elko
x12_elmira-corning
x12_erie
x12_eugene
x12_evansville
x12_fairbanks
x12_fargo / moorhead
x12_farmington
x12_fayetteville
x12_finger lakes
x12_flagstaff / sedona
x12_flint
x12_florence
x12_florence / muscle shoals
x12_florida keys
x12_fort collins / north CO
x12_fort dodge
x12_fort smith
x12_fort wayne
x12_frederick
x12_fredericksburg
x12_fresno / madera
x12_ft myers / SW florida
x12_gadsden-anniston
x12_gainesville
x12_galveston
x12_glens falls
x12_gold country
x12_grand forks
x12_grand island
x12_grand rapids
x12_great falls
x12_green bay
x12_greensboro
x12_greenville / upstate
x12_gulfport / biloxi
x12_hanford-corcoran
x12_harrisburg
x12_harrisonburg
x12_hartford
x12_hattiesburg
x12_hawaii
x12_heartland florida
x12_helena
x12_hickory / lenoir
x12_high rockies
x12_hilton head
x12_holland
x12_houma
x12_houston
x12_hudson valley
x12_humboldt county
x12_huntington-ashland
x12_huntsville / decatur
x12_imperial county
x12_indianapolis
x12_inland empire
x12_iowa city
x12_ithaca
x12_jackson
x12_jacksonville
x12_janesville
x12_jersey shore
x12_jonesboro
x12_joplin
x12_kalamazoo
x12_kalispell
x12_kansas city, MO
x12_kenai peninsula
x12_kennewick-pasco-richland
x12_kenosha-racine
x12_killeen / temple / ft hood
x12_kirksville
x12_klamath falls
x12_knoxville
x12_kokomo
x12_la crosse
x12_la salle co
x12_lafayette
x12_lafayette / west lafayette
x12_lake charles
x12_lake of the ozarks
x12_lakeland
x12_lancaster
x12_lansing
x12_laredo
x12_las cruces
x12_las vegas
x12_lawrence
x12_lawton
x12_lehigh valley
x12_lewiston / clarkston
x12_lexington
x12_lima / findlay
x12_lincoln
x12_little rock
x12_logan
x12_long island
x12_los angeles
x12_louisville
x12_lubbock
x12_lynchburg
x12_macon / warner robins
x12_madison
x12_maine
x12_manhattan
x12_mankato
x12_mansfield
x12_mason city
x12_mattoon-charleston
x12_mcallen / edinburg
x12_meadville
x12_medford-ashland
x12_memphis
x12_mendocino county
x12_merced
x12_milwaukee
x12_minneapolis / st paul
x12_missoula
x12_mobile
x12_modesto
x12_mohave county
x12_monroe
x12_monterey bay
x12_montgomery
x12_morgantown
x12_moses lake
x12_muncie / anderson
x12_muskegon
x12_myrtle beach
x12_nashville
x12_new hampshire
x12_new haven
x12_new orleans
x12_new river valley
x12_new york city
x12_norfolk / hampton roads
x12_north central FL
x12_north dakota
x12_north jersey
x12_north mississippi
x12_north platte
x12_northeast SD
x12_northern WI
x12_northern michigan
x12_northern panhandle
x12_northwest CT
x12_northwest GA
x12_northwest KS
x12_northwest OK
x12_ocala
x12_odessa / midland
x12_ogden-clearfield
x12_okaloosa / walton
x12_oklahoma city
x12_olympic peninsula
x12_omaha / council bluffs
x12_oneonta
x12_orange county
x12_oregon coast
x12_orlando
x12_outer banks
x12_owensboro
x12_palm springs
x12_panama city
x12_parkersburg-marietta
x12_pensacola
x12_peoria
x12_philadelphia
x12_phoenix
x12_pierre / central SD
x12_pittsburgh
x12_plattsburgh-adirondacks
x12_poconos
x12_port huron
x12_portland
x12_potsdam-canton-massena
x12_prescott
x12_pueblo
x12_pullman / moscow
x12_quad cities, IA/IL
x12_raleigh / durham / CH
x12_rapid city / west SD
x12_reading
x12_redding
x12_reno / tahoe
x12_rhode island
x12_richmond
x12_roanoke
x12_rochester
x12_rockford
x12_roseburg
x12_roswell / carlsbad
x12_sacramento
x12_saginaw-midland-baycity
x12_salem
x12_salina
x12_salt lake city
x12_san angelo
x12_san antonio
x12_san diego
x12_san luis obispo
x12_san marcos
x12_sandusky
x12_santa barbara
x12_santa fe / taos
x12_santa maria
x12_sarasota-bradenton
x12_savannah / hinesville
x12_scottsbluff / panhandle
x12_scranton / wilkes-barre
x12_seattle-tacoma
x12_sheboygan
x12_show low
x12_shreveport
x12_sierra vista

# Modeling

In [179]:
df_pr = pd.read_csv('data/vehicles_dataset_prepared.csv')

df_prepared = df_pr.copy()
df_prepared = df_prepared.drop(['price'], axis=1)

x = df_prepared.drop(['price_category'], axis=1)
y = df_prepared['price_category']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

## Логистическая регрессия

In [79]:
logreg = LogisticRegression(penalty='none', max_iter=300, solver='saga')
logreg.fit(x_train, y_train)

J:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "

LogisticRegression(max_iter=300, penalty='none', solver='saga')

In [80]:
logreg_pred = logreg.predict(x_train)
print(accuracy_score(y_train, logreg_pred))

0.8436413125661576

In [81]:
logreg_pred_test = logreg.predict(x_test)
print(accuracy_score(y_test, logreg_pred_test))
confusion_matrix(y_test, logreg_pred_test)

0.7693121693121693

array([[850,  22, 143],
       [ 27, 697, 167],
       [126, 169, 634]], dtype=int64)

## Случайнай лес

In [186]:
rf_clf = RandomForestClassifier(bootstrap=False, max_features='log2', n_estimators=500, random_state=42)
rf_clf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=False, max_features='log2', n_estimators=500,
                       random_state=42)

In [181]:
pred_rf = rf_clf.predict(x_train)
print(accuracy_score(y_train, pred_rf))

0.999848782700741

In [182]:
rf_pred_test = rf_clf.predict(x_test)
print(accuracy_score(y_test, rf_pred_test))
confusion_matrix(y_test, rf_pred_test)

0.7763668430335097

array([[864,  22, 129],
       [ 11, 755, 125],
       [131, 216, 582]], dtype=int64)

## Многослойный персептрон

In [217]:
mlp = MLPClassifier(random_state=42, max_iter=500)
mlp.fit(x_train, y_train)

MLPClassifier(max_iter=500, random_state=42)

In [218]:
mlp_pred = mlp.predict(x_train)
print(accuracy_score(y_train, mlp_pred))

0.999848782700741

In [219]:
mlp_pred_test = mlp.predict(x_test)
print(accuracy_score(y_test, mlp_pred_test))
confusion_matrix(y_test, mlp_pred_test)

0.780952380952381

array([[871,  28, 116],
       [ 19, 711, 161],
       [125, 172, 632]], dtype=int64)

## Results

In [188]:
#Модель случайного леса на тестовой выборке показала себя наилучшим образом

#Проверим модель на переобучение
cv_score = cross_validate(rf_clf, x, y, cv=5)

In [194]:
cv_score['test_score'].mean(), cv_score['test_score'].std()

(0.8029210606658992, 0.004368015384377835)

In [ ]:
#Модель не переобучилась, отклонение получилось небольшим.

In [195]:
#Обучтм модель на всем дата сете
rf_clf.fit(x, y)

RandomForestClassifier(bootstrap=False, max_features='log2', n_estimators=500,
                       random_state=42)

In [196]:
filename = 'model.pickle'
with open (filename, 'wb') as file:
    pickle.dump(rf_clf, file)

In [198]:
model_from_pickle

RandomForestClassifier(bootstrap=False, max_features='log2', n_estimators=500,
                       random_state=42)